Ursus/urls.py
from django.conf.urls import patterns, include, url
from django.contrib.staticfiles.urls import static
from django.conf import settings
from two_factor.urls import urlpatterns as tf_urls

urlpatterns = patterns('',
	url(r'', include('authy.urls', 'authy')),
	url(r'^$', include('dashboard.urls', 'dashboard')),
	url(r'^registro/$', 'users.views.registry_client', name='registry'),
	url(r'^registro/continuar/$', 'users.views.new_profile', name='new_profile'),
	url(r'^admin/', include('admin.urls', 'admin')),
	url(r'^requisiciones/', include('requisitions.urls', 'reqs')),
	url(r'^estudios/', include('studies.urls', 'studies')),
	url(r'^reportes/', include('reports.urls', 'reports')),
	url(r'^configuracion/', include('settings.urls', 'settings')),

	url(r'^redactor/', include('redactor.urls')),
	
	url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {
        'document_root': settings.MEDIA_ROOT,
    }),

    url(r'', include(tf_urls, 'two_factor')),
    url(r'', include('user_sessions.urls', 'user_sessions')),
) + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

requisitions/urls.py
from django.conf.urls import patterns, include, url

urlpatterns = patterns(
    '',
    url(r'^$', 'requisitions.views.home', name='home'),
    url(r'^nueva/$', 'requisitions.views.create_req', name='new_req'),
    url(r'^ver/(?P<req_id>\d+)/$', 'requisitions.views.view_req', name='view_req'),
    url(r'^bajar-adjuntos/(?P<req_id>\d+)/$', 'requisitions.views.download', name='download'),
    url(r'^editar/(?P<req_id>\d+)/$', 'requisitions.views.edit_req', name='edit_req'),

    url(r'^(?P<req_id>\d+)/crear-estudio/$', 'studies.views.create_study', name='create_study'),

)

requisitions/models.py
#encoding: utf-8
from django.db import models
from django.contrib.auth.models import User
from redactor.fields import RedactorField
from users.models import Role

REQ_STATUS = (
	('R','Registrada'),
	('P','En proceso'),
	('T','Terminada'),
)

class Requisition(models.Model):
	open_date = models.DateTimeField(auto_now=True)
	client = models.ForeignKey(User, verbose_name=u'Cliente', on_delete=models.PROTECT)
	limit_date = models.DateTimeField(verbose_name=u'Fecha Límite')
	description = RedactorField(verbose_name=u'Descripción')
	status = models.CharField(max_length=1, default='R', verbose_name=u'Estado', choices=REQ_STATUS)

	def __unicode__(self):
		return u'Requisición #'+str(self.id)

class Service(models.Model):
	name = models.CharField(max_length=60, verbose_name=u'Nombre', unique=True)
	description = RedactorField(verbose_name=u'Descripción')
	roles = models.ManyToManyField(Role, verbose_name='Cargos involucrados')

	def __unicode__(self):
		return self.name

	class Meta:
		verbose_name = u'Servicio'


def get_path(instance,file):
	dir = '/'
	if instance.file_type == 'CV':
		dir = '/curriculums/'
	elif instance.file_type == 'BO':
		dir = '/orders/'
	return 'uploads/requisitions/'+str(instance.requisition.id)+dir+file

import os
class Atachment(models.Model):
	TYPES = (
		('CV','Hoja de vida'),
		('BO','Orden de Compra'),
		('RE','Resumen'),
	)
	requisition = models.ForeignKey(Requisition, on_delete=models.CASCADE)
	file_type = models.CharField(max_length=2, verbose_name=u'Tipo de adjunto', choices=TYPES)
	file_resource = models.FileField(upload_to=get_path)

	def get_size(self):
		return self.file_resource.file.size

	def __unicode__(self):
		return u''+os.path.basename(self.file_resource.file.name)

studies/models.py
#encoding: utf-8
from django.db import models
from django_resized import ResizedImageField
from django.core.validators import RegexValidator, MinLengthValidator, MaxLengthValidator
from requisitions.models import Requisition, Service
from django.contrib.auth.models import User
from redactor.fields import RedactorField

STUDY_STATUS = (
	('A','Asignado'),
	('R','En revisión'),
	('F','Terminado'),
)

def get_path(instance,file):
	return 'uploads/studies/'+str(instance.id)+file

class Study(models.Model):
	creation_date = models.DateTimeField(auto_now=True)
	requisition = models.ForeignKey(Requisition, verbose_name=u'Requisición', on_delete=models.CASCADE)
	service = models.ForeignKey(Service, verbose_name=u'Servicio')
	employee = models.ForeignKey(User, verbose_name=u'Empleado')
	limit_date = models.DateTimeField(verbose_name=u'Fecha de Entrega')
	description = RedactorField(verbose_name=u'Descripción')
	attachment = models.FileField(upload_to=get_path, verbose_name=u'Archivos adjuntos')
	observations = RedactorField(verbose_name=u'Observaciones', blank=True, null=True)
	status = models.CharField(max_length=1, default='A', verbose_name=u'Estado', choices=STUDY_STATUS)

requisitions/forms.py
from django import forms
from models import Requisition, Service
from django.contrib.auth.models import User

class AddRequisitionForm(forms.ModelForm):
	class Meta:
		model = Requisition
		fields = '__all__'
		exclude = ['status']
		
	def __init__(self, *args, **kwargs):
		super(AddRequisitionForm, self).__init__(*args, **kwargs)
		
		if kwargs.get('initial'):
			client = kwargs.get('initial').get('client')
			self.fields['client'].choices = [(client.id, client.first_name+' '+client.last_name)]
		else:	
			excluded = User.objects.filter(type='C')
			self.fields['client'].choices = [(p.id, p.first_name+' '+p.last_name,) for p in excluded]
			self.fields['client'].choices = [('', '---------')]+self.fields['client'].choices

class ServiceForm(forms.ModelForm):
	class Meta:
		model = Service
		
		fields = '__all__'
 

requisitions/views.py
#encoding: utf-8
from django.shortcuts import render_to_response, redirect
from django.template import RequestContext
from django.contrib.auth.models import User
from requisitions.models import Atachment

from users.models import Notification
from models import Requisition
from forms import AddRequisitionForm
from django.core.urlresolvers import reverse_lazy

def home(request):
	reqs = ''
	if request.user.is_superuser or request.user.is_staff:
		reqs = Requisition.objects.all()
	else:
		reqs = Requisition.objects.filter(client=request.user)

	reqs = reqs.order_by('-open_date')
	return render_to_response('index_reqs.html', {'reqs':reqs}, context_instance=RequestContext(request))

def create_req(request):

	if request.method == 'GET':
		if request.user.type == 'C':
			form = AddRequisitionForm(initial={'client': request.user})
		else:
			form = AddRequisitionForm()
		return render_to_response('requisition.html', {'form':form}, context_instance=RequestContext(request))

	if request.method == 'POST':
		form = AddRequisitionForm(request.POST)
		if form.is_valid():
			new_req = form.save()

			if request.FILES:
				files = request.FILES
				if hasattr(files, 'getlist'):
					cv_files = files.getlist('curriculums')
					save_attachements(new_req, 'CV', cv_files)

					orders = files.getlist('orders')
					save_attachements(new_req, 'BO', orders)

					resume = files.get('resume')
					if resume:
						save_attachements(new_req, 'RE', [resume])
					

			notificate_requisition(new_req.client, new_req.id)
			return redirect(reverse_lazy('reqs:view_req', args=(new_req.id,)))

		return render_to_response('requisition.html', {'form':form}, context_instance=RequestContext(request))

def view_req(request, req_id):
	req = Requisition.objects.get(id=req_id)

	if request.GET.get('notif'):
		not_id = request.GET.get('notif')
		notif = Notification.objects.get(id=not_id)
		notif.status=True
		notif.save()
		print notif

	return render_to_response('req_detail.html', {'req':req}, context_instance=RequestContext(request))

def edit_req(request, req_id):

	if request.method == 'GET':
		req = Requisition.objects.get(id=req_id)
		form = AddRequisitionForm(instance=req)
		return render_to_response('requisition.html', {'form':form, 'editing':True, 'id': req_id}, context_instance=RequestContext(request))
	
	if request.method == 'POST':
		req = Requisition.objects.get(id=req_id)
		form = AddRequisitionForm(request.POST, instance=req)
		if form.is_valid():
			new_req = form.save()

			if request.FILES:
				files = request.FILES
				if hasattr(files, 'getlist'):
					cv_files = files.getlist('curriculums')
					if cv_files:
						req.atachment_set.filter(file_type='CV').delete()
						save_attachements(new_req, 'CV', cv_files)
					
					orders = files.getlist('orders')
					if orders:
						req.atachment_set.filter(file_type='BO').delete()
						save_attachements(new_req, 'BO', orders)

					resume = files.get('resume')
					if resume:
						save_attachements(new_req, 'RE', [resume])
			
			return redirect(reverse_lazy('reqs:view_req', args=(new_req.id,)))
	
		return render_to_response('requisition.html', {'form':form, 'editing':True, 'id': req_id}, context_instance=RequestContext(request))

from django.core.mail import send_mail

def notificate_requisition(site_user, element_id):
	users = User.objects.filter(is_superuser=True)

	mails = []
	for user in users:
		mails.append(user.email)

		notification = Notification(
				a_tag='',
				user=user,
				message='El cliente '+site_user.first_name+' '+site_user.last_name+' ha registrado una nueva requisición.</a>'.decode('utf-8'),
				short=u"Nueva requisición",
				icon="fa fa-book"
			)
		notification.save()
		notification.a_tag='<a href="/requisiciones/ver/'+str(element_id)+'?notif='+str(notification.id)+'">'
		notification.save()

	send_mail(
		subject=u'Nueva requisición registrada', 
		message='El cliente '+site_user.first_name+' '+site_user.last_name+' ha registrado una nueva requisicion.',
		html_message='<p>El cliente <b>'+site_user.first_name+' '+site_user.last_name+'</b> ha registrado una nueva requisicion. <a href="ursus.cosegem.com/requisiciones/ver/'+str(element_id)+'?notif='+str(notification.id)+'">Ver requisicion</a></p>'.decode('utf-8'),
		from_email='Ursus <notificaciones.ursus@cosegem.com>',
		recipient_list=mails,
		fail_silently=False 
	)



def save_attachements(requisition, type, files):
	for file in files:
		new_attachement = Atachment(requisition=requisition, file_type=type, file_resource=file)
		new_attachement.save()

from shutil import make_archive
from django.core.servers.basehttp import FileWrapper
from django.conf import settings
from django.http import HttpResponse

def download(request, req_id):
    file_path = settings.MEDIA_ROOT+'/uploads/requisitions/'+req_id+'/'
    print file_path

    path_to_zip = make_archive(file_path,"zip",file_path)
    response = HttpResponse(FileWrapper(file(path_to_zip,'rb')), content_type='application/zip')
    response['Content-Disposition'] = 'attachment; filename=requisicion_'+req_id+'.zip'
    return response

requisitions/templates/index_reqs.html
{% extends "base.html" %}
{% load static %}
{% load study_tags %}

{% block imports %}
  <link href="{% static "css/chosen.min.css" %}" rel="stylesheet">
  <link href="{% static "css/chosen-bootstrap.css" %}" rel="stylesheet">
  <link href="{% static "css/bootstrap-sortable.css" %}" rel="stylesheet">
{% endblock %}

{% block title %} Requisiciones {% endblock %}

{% block content %}
	<div class="row mt">
		<div class="col-lg-12">
      <h3 class="inline" style="padding-left:20px;">
        <i class="fa fa-book"></i> 
          Requisiciones <small>({{reqs.count}} requisiciones)</small>
      </h3>
      <hr style="border-color:#ddd;">
      <div class="row-fluid actions-bar">
        {% if user.is_superuser or user.is_staff or user.type == 'C'%}
          <a href="{% url "reqs:new_req"%}" class="btn btn-success">Agregar Requisición </a>
        {% else %}
          <b style="margin-right:10px;">Buscar: </b>
        {% endif %}
        <select id="search-box" class="form-control chosen-select">
          <option></option>
          {% for req in reqs %}
            <option data-href="{% url "reqs:view_req" req.id %}">
                Requisición #{{req.id}}
            </option>
          {% endfor %}
        </select>

      </div>
      <section id="unseen">
        <table class="table table-striped sortable">
          <thead>
            <tr>
              <th class="text-center">Nombre</th>
              <th class="text-center">Fecha</th>
              <th class="text-center hidden-xs">Cliente</th>
              <th class="text-center hidden-xs">Estado</th>
              <th class="text-center hidden-xs">Progreso</th>
            </tr>
          </thead>
          <tbody>
            {% if reqs %}
              {% for req in reqs %}
                <tr>
                  <td class="text-center">
                    <a href="{% url "reqs:view_req" req.id %}">
                      Requisición #{{req.id}}
                    </a>
                  </td>
                  <td class="text-center">
                    {{req.open_date}}
                  </td>
                  <td class="text-center hidden-xs">{{req.client}}</td>
                  <td class="text-center hidden-xs">
                    {{req.get_status_display}}
                  </td>
                  <td class="text-center hidden-xs">
                  {% if req.status == 'P' %}
                      <div class="progress" style="margin-bottom:0;">
                        <div class="progress-bar text-center" role="progressbar" aria-valuenow="60" aria-valuemin="0" aria-valuemax="100" style="width: {{req.id|get_progress}}%;">
                          {{req.id|get_progress}}%
                        </div>
                      </div>  
                  {% endif %}
                  </td>
                </tr>            
              {% endfor %}
            {% else %}
              <tr>
                <td colspan="9" class="text-center">
                  <p class="alert alert-info">
                    No hay requisiciones registradas
                  </p>
                </td>
              </tr>
            {% endif %}   
          </tbody>
        </table>
      </section>
    </div>
	</div>
{% endblock %}

{% block js_imports %}
  <script type="text/javascript" src="{% static "js/bootstrap-sortable.js" %}"></script>
  <script type="text/javascript" src="{% static "js/chosen.jquery.min.js" %}"></script>
{% endblock %}

requisitions/templates/massive-load.html
{% extends "base.html"%}
{% load static %}

{% block title %}
	Cargar Masiva
{% endblock %}

{% block imports %}
	<link href="{% static "css/chosen.min.css" %}" rel="stylesheet">
    <link href="{% static "css/chosen-bootstrap.css" %}" rel="stylesheet">
{% endblock %}

{% block content %}
	<h3 style="padding-left:20px;margin-top:50px;">
		<i class="fa fa-upload"></i> 
		Carga Masiva
	</h3>
	<hr style="border-color:#ddd;">


	<form class="form-horizontal col-md-10" id="add_user" method="POST" action="." enctype="multipart/form-data">
			{% csrf_token %}
				<div class="form-group">
				    <label class="col-sm-2 control-label">
				    	Archivo CSV
				    </label>
				    <div class="col-sm-10" style="margin-top:20px;">
				    	<input class="file" type="file" name="csv_file"/>
				    </div>
			  	</div>
			
			<p class="text-right">
				<a href="{% url "reqs:home" %}" class="btn btn-default" >Cancelar</a>
				<button type="submit" class="btn btn-primary" >
					{% if editing %}
						Guardar cambios
					{% else %}
						Crear Requisición
					{% endif %}
				</button>
			</p>
		</form>

{% endblock %}



{% block js_imports%}
	<script type="text/javascript" src="{% static "js/chosen.jquery.min.js" %}"></script>
{% endblock %}

requisitions/templates/req_detail.html
{% extends "base.html" %}
{% load static %}
{% load humanize %}

{% block title %} Requisición #{{req.id}} {% endblock %}

{% block content %}
	<div class="row mt">
		<div class="col-lg-12">
	      	<h3 class="inline" style="padding-left:20px;">
	        	<i class="fa fa-book"></i> 
	          	Requisición #{{req.id}} <small>(Registrada por {{req.client.first_name}} {{req.client.last_name}})</small>
	      	</h3>
	      	<hr style="border-color:#ddd;">

	      	<div class="row mt">
				<div class="col-lg-12">
					<div class="resume col-lg-7 col-md-7 col-sm-7 col-xs-12">
						<div class="col-lg-12">
							<!-- WHITE PANEL - TOP USER -->
							<div class="white-panel pn">
								<div class="white-header">
									<h5>RESUMEN</h5>
								</div>
								
								<div class="row">
									<div class="col-md-5">
										<p><small>Solicitado por:</small></p>
										<p>
											<img src="{{MEDIA_URL}}{{ req.client.avatar }}" class="img-circle" width="50">
										</p>
										<p><b>{{req.client.first_name}} {{req.client.last_name}}</b></p>
									</div>
									<div class="col-md-6" style="margin-bottom:20px;">
										<a href="{% url "reqs:edit_req" req.id %}" class="btn btn-primary" style="width:80%">
											Modificar
										</a>
									</div>
									<div class="col-md-3">
										<p class="small mt">FECHA</p>
										<p>{{req.open_date|date:"M d, Y"}}</p>
									</div>
									<div class="col-md-3">
										<p class="small mt">TIEMPO RESTANTE</p>
										<p class="remove-msg">{{req.limit_date|naturaltime}}</p>
									</div>
									<div class="col-md-7">
										<p class="small mt">ESTADO</p>
										<p>
											{{req.get_status_display}}
										</p>
									</div>
									

									<div class="col-md-10 col-md-offset-1">
										<p class="small mt">DESCRIPCIÓN DE LA REQUISICIÓN</p>
										<div class="desc-panel panel panel-default">
										  <div class="panel-body">
										    {{req.description|safe}}
										  </div>
										</div>
									</div>
								</div>
							</div>
						</div>
					</div> 
					<div class="resume col-lg-5 col-md-5 col-sm-5 col-xs-12">
						<div class="col-lg-12">
							<!-- WHITE PANEL - TOP USER -->
							<div class="white-panel pn">
								<div class="white-header">
									<h5>ARCHIVOS ADJUNTOS</h5>
								</div>
								<div class="row">
                                    <div class="col-md-10 col-md-offset-1">
                                        <div class="panel-group" style="max-height:491px;" id="accordion" role="tablist" aria-multiselectable="true">
                                            <div class="panel panel-default">
                                                <div class="panel-heading" role="tab" id="headingOne">
                                                    <h4 class="panel-title">
                                                        <a data-toggle="collapse" data-parent="#accordion" href="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
                                                            Hojas de Vida
                                                        </a>
                                                    </h4>
                                                </div>
                                                <div id="collapseOne" class="panel-collapse collapse in" role="tabpanel" aria-labelledby="headingOne">
                                                    <div class="panel-body text-left" style="max-height:274px;overflow:auto;">
                                                        {% for attach in req.atachment_set.all %}
                                                            {% if attach.file_type == 'CV' %}
                                                                <p>
                                                                    <a class="btn-link" target="_blank" href="/media/{{attach.file_resource}}">
                                                                        {% if attach %}{{attach}} ({{attach.get_size|filesizeformat}}){%endif%}
                                                                    </a>
                                                                </p>
                                                            {% endif %}
                                                        {% endfor %}
                                                    </div>
                                                </div>
                                            </div>
                                            <div class="panel panel-default">
                                                <div class="panel-heading" role="tab" id="headingTwo">
                                                    <h4 class="panel-title">
                                                        <a class="collapsed" data-toggle="collapse" data-parent="#accordion" href="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
                                                            Ordenes de Compra
                                                        </a>
                                                    </h4>
                                                </div>
                                                <div id="collapseTwo" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingTwo">
                                                    <div class="panel-body text-left" style="max-height:274px;overflow:auto;">
                                                        {% for attach in req.atachment_set.all %}
                                                            {% if attach.file_type == 'BO' %}
                                                            <p>
                                                                <a class="btn-link" target="_blank" href="/media/{{attach.file_resource}}">
                                                                    {% if attach %}{{attach}} ({{attach.get_size|filesizeformat}}){%endif%}
                                                                </a>
                                                            </p>
                                                            {% endif %}
                                                        {% endfor %}
                                                    </div>
                                                </div>
                                            </div>
                                            <div class="panel panel-default">
                                                <div class="panel-heading" role="tab" id="headingThree">
                                                    <h4 class="panel-title">
                                                        <a class="collapsed" data-toggle="collapse" data-parent="#accordion" href="#collapseThree" aria-expanded="false" aria-controls="collapseThree">
                                                            Otros
                                                        </a>
                                                    </h4>
                                                </div>
                                                <div id="collapseThree" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingThree">
                                                    <div class="panel-body text-left" style="max-height:274px;overflow:auto;">
                                                        {% for attach in req.atachment_set.all %}
                                                            {% if attach.file_type == 'RE' %}
                                                            {{attach.file_type}}
                                                            <p>
                                                                <a class="btn-link" target="_blank" href="/media/{{attach.file_resource}}">
                                                                    {% if attach %}{{attach}} ({{attach.get_size|filesizeformat}}){%endif%}
                                                                </a>
                                                            </p>
                                                            {% endif %}
                                                        {% endfor %}
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="row">
									<a class="btn btn-success" href="{% url 'reqs:download' req.id %}">
										<span class="fa fa-download"></span> Bajar todo como zip
									</a>
								</div>
							</div>
						</div>
					</div>

                    <div class="resume col-lg-12 col-md-12 col-sm-12 col-xs-12">
						<div class="col-lg-12">
							<!-- WHITE PANEL - TOP USER -->
							<div class="white-panel pn">
								<div class="white-header">
									<h5>ESTUDIOS ASIGNADOS</h5>
								</div>

								<div class="col-md-12">
									<table class="table table-striped">
										<thead>
								            <tr>
								              <th class="text-center">Estudio</th>
								              <th class="text-center">Estado</th>
								              <th class="text-center">Fecha de Asignación</th>
								              <th class="text-center">Tiempo para entrega</th>
								            </tr>
								          </thead>
								          <tbody>
								            {% if req.study_set.all %}
								              {% for study in req.study_set.all %}
								                <tr>
								                  <td class="text-center">
								                    <a href="{% url "studies:view_study" study.id%}">
								                      Estudio #{{study.id}}
								                    </a>
								                  </td>
								                  <td class="text-center">
								                    {{study.get_status_display}}
								                  </td>
								                  <td class="text-center">
								                    {{study.creation_date}}
								                  </td>
								                  <td class="text-center remove-msg">
								                    {{study.limit_date|naturaltime}}
								                  </td>
								                </tr>
								              {% endfor %}
								            {% else %}
								              <tr>
								                <td colspan="4" class="text-center">
								                  <p class="alert alert-info">
								                    No se ha asignado ningún estudio
								                  </p>
								                </td>
								              </tr>
								            {% endif %}
								          </tbody>
									</table>
								</div>

								<div class="row">
									<p style="margin-top:25px;">
									{% if user.is_superuser or user.is_staff %}
										<a href="{% url "reqs:create_study" req.id %}" class="btn btn-primary">
											Asignar Estudios
										</a>
									{% endif %}
									</p>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
    	</div>
	</div>
{% endblock %}

{% block js_imports%}
<script type="text/javascript">
	$(document).ready(function(){
		$('table').addClass('table table-bordered');
		
		$.each($('.remove-msg'), function(){
			$(this).html($(this).html().replace('a partir de ahora', ''));
		});

	});
</script>
{% endblock %}

requisitions/templates/requisition.html
{% extends "base.html"%}
{% load static %}

{% block title %}
	{% if editing %}
		Editar Requisición
	{% else %}
		Agregar Requisición
	{% endif %}
{% endblock %}

{% block imports %}
	<link href="{% static "css/chosen.min.css" %}" rel="stylesheet">
    <link href="{% static "css/chosen-bootstrap.css" %}" rel="stylesheet">
    <link href="{% static "css/bootstrap-datetimepicker.css" %}" rel="stylesheet">
{% endblock %}

{% block content %}
	<h3 style="padding-left:20px;"><i class="fa fa-book"></i> 
		{% if editing %}
			Editar Requisición #{{id}}
		{% else %}
			Agregar Requisición
		{% endif %}
	</h3>
	<hr style="border-color:#ddd;">


	<form class="form-horizontal col-md-10" id="add_user" method="POST" action="." enctype="multipart/form-data">
			{% csrf_token %}
			{% for field in form %}
				<div class="form-group">
				    <label class="col-sm-2 control-label">
				    	{{field.label}}
				    </label>
				    <div class="col-sm-10" style="margin-top:20px;">
				    	{% for error in field.errors %}
			    			<p class="text-danger">
			    				{{error.capitalize}}
			    			</p>
			    		{% endfor %}
				      	{{field}}
				    </div>
			  	</div>
			{% endfor %}
            <div class="form-group">
                <label class="col-sm-2 control-label">
                    Hojas de vida
                </label>
                <div class="col-sm-10" style="margin-top:20px;">
                    <input type="file" name="curriculums" multiple/>
                </div>
            </div>

            <div class="form-group">
                <label class="col-sm-2 control-label">
                    Órdenes de Compra
                </label>
                <div class="col-sm-10" style="margin-top:20px;">
                    <input type="file" name="orders" multiple/>
                </div>
            </div>

            <div class="form-group">
                <label class="col-sm-2 control-label">
                    Resumen de Servicios (Excel)
                </label>
                <div class="col-sm-10" style="margin-top:20px;">
                    <input type="file" name="resume"/>
                </div>
            </div>

			<p class="text-right">
				{% if editing %}
				<a href="{% url "reqs:view_req" id %}" class="btn btn-default" >Cancelar</a>
				{% else %}
				<a href="{% url "reqs:home" %}" class="btn btn-default" >Cancelar</a>
				{% endif %}
				<button type="submit" class="btn btn-primary" >
					{% if editing %}
						Guardar cambios
					{% else %}
						Crear Requisición
					{% endif %}
				</button>
			</p>
		</form>

{% endblock %}



{% block js_imports%}

	<script type="text/javascript" src="{% static "js/chosen.jquery.min.js" %}"></script>
	<script type="text/javascript" src="{% static "js/moment-with-locales.js" %}"></script>
	<script type="text/javascript" src="{% static "js/bootstrap-datetimepicker.js" %}"></script>
	<script type="text/javascript">
	  	$(document).ready(function(){
	  			
	  		$('#id_limit_date').parent().append(
		  		'<div class="input-group date" id="datetimepicker">\
	                <span class="input-group-addon">\
	                    <span class="glyphicon glyphicon-calendar"></span>\
	                </span>\
	            </div>'
		  	);
		  	$('#id_limit_date').prependTo('#datetimepicker');

		  	$('#datetimepicker').datetimepicker({'format':'DD/MM/YYYY HH:mm', sideBySide:true, locale:'es-CO'});
	  	});

	</script>
	{{ form.media }}

{% endblock %}