Ursus/urls.py
from django.conf.urls import patterns, include, url
from django.contrib.staticfiles.urls import static
from django.conf import settings
from two_factor.urls import urlpatterns as tf_urls

urlpatterns = patterns('',
	url(r'', include('authy.urls', 'authy')),
	url(r'^$', include('dashboard.urls', 'dashboard')),
	url(r'^registro/$', 'users.views.registry_client', name='registry'),
	url(r'^registro/continuar/$', 'users.views.new_profile', name='new_profile'),
	url(r'^admin/', include('admin.urls', 'admin')),
	url(r'^requisiciones/', include('requisitions.urls', 'reqs')),
	url(r'^estudios/', include('studies.urls', 'studies')),
	url(r'^reportes/', include('reports.urls', 'reports')),
	url(r'^configuracion/', include('settings.urls', 'settings')),

	url(r'^redactor/', include('redactor.urls')),
	
	url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {
        'document_root': settings.MEDIA_ROOT,
    }),

    url(r'', include(tf_urls, 'two_factor')),
    url(r'', include('user_sessions.urls', 'user_sessions')),
) + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

reports/urls.py
from django.conf.urls import patterns, include, url

urlpatterns = patterns(
    '',
    url(r'^(?P<study_id>\d+)/nuevo/$', 'reports.views.report_router', name='new_report'),
    
    
    url(r'^(?P<study_id>\d+)/reporte-antecedentes/$', 'reports.views.create_legal_report', name='new_legal_report'),
    url(r'^(?P<study_id>\d+)/reporte-seguridad/$', 'reports.views.create_verification_report', name='new_verif_report'),
    
    url(r'^ver/(?P<report_id>\d+)/$', 'reports.views.view_report', name='view_report'),
    url(r'^editar/(?P<report_id>\d+)/$', 'reports.views.edit_report', name='edit_report'),
    url(r'^bloquear/(?P<report_id>\d+)/$', 'reports.views.lock_report', name='lock_report'),
    url(r'^desbloquear/(?P<report_id>\d+)/$', 'reports.views.unlock_report', name='unlock_report'),
    url(r'^eliminar/(?P<report_id>\d+)/$', 'reports.views.delete_report', name='remove_report'),
    url(r'^publicar/(?P<report_id>\d+)/$', 'reports.views.check_report', name='check_report'),



    url(r'^(?P<study_id>\d+)/subir/$', 'reports.views.upload_report', name='upload_report'),
    url(r'^editar-subido/(?P<ureport_id>\d+)/$', 'reports.views.edit_upload_report', name='edit_report_upload'),
    url(r'^bloquear-subido/(?P<report_id>\d+)/$', 'reports.views.lock_upload_report', name='lock_report_upload'),
    url(r'^desbloquear-subido/(?P<report_id>\d+)/$', 'reports.views.unlock_upload_report', name='unlock_report_upload'),
    url(r'^eliminar-subido/(?P<report_id>\d+)/$', 'reports.views.delete_upload_report', name='remove_report_upload'),
    url(r'^publicar-subido/(?P<report_id>\d+)/$', 'reports.views.check_upload_report', name='check_report_upload'),

    url(r'^buscar/$', 'reports.views.search', name='search'),
    url(r'^buscar/por-requisicion/(?P<req_id>\d+)/$', 'reports.views.search_by_req', name='search_req'),
    url(r'^reporte-completo/(?P<dni>\d+)/$', 'reports.views.join_reports', name='join_reports'),
    url(r'^comprimir/(?P<req_id>\d+)/$', 'reports.views.compress_reports', name='compress_reports'),
)

reports/models.py
#encoding: utf-8
from django.db import models
from studies.models import Study

# Create your models here.

REPORT_CHOICES = (
	('HV','Visita Domiciliaria'),
	('LS','Situación Jurídica'),
	('SS','Estudio de Seguridad'),
)

def get_path(instance,file):
	return 'uploads/reports/'+str(instance.candidate.dni_number)+"/"+file


class Candidate(models.Model):
	dni_number = models.CharField(max_length=20)
	class Meta:
		def __unicode__():
			return dni_number

class ReportForm(models.Model):
	study = models.ForeignKey(Study)
	candidate = models.ForeignKey(Candidate)
	json_data = models.TextField()
	report_type = models.CharField(max_length=2, choices=REPORT_CHOICES)
	locked = models.BooleanField(default=False)
	verified = models.BooleanField(default=False)

class ReportFile(models.Model):
	study = models.ForeignKey(Study)
	candidate = models.ForeignKey(Candidate, verbose_name=u'Cédula candidato')
	report_file = models.FileField(upload_to=get_path, verbose_name=u'Archivo')
	report_type = models.CharField(max_length=2, choices=REPORT_CHOICES, verbose_name=u'Tipo de reporte')
	locked = models.BooleanField(default=False)
	verified = models.BooleanField(default=False)

reports/forms.py
#encoding: utf-8
from django import forms
from reports.models import ReportFile
import django.forms.widgets as widgets
from django.core.validators import RegexValidator, MinLengthValidator, MaxLengthValidator
from reports.models import Candidate

REPORT_TYPES = (
	#('HV','Visita Domiciliaria'),
	('LS','Situación Jurídica'),
	('SS','Estudio de Seguridad'),
)

REPORT_TYPES_B = (
	('HV','Visita Domiciliaria'),
	('LS','Situación Jurídica'),
	('SS','Estudio de Seguridad'),
)

class ReportRouterForm(forms.Form):
	report_type = forms.ChoiceField(choices=REPORT_TYPES, label=u'Tipo de reporte')


class ReportFileForm(forms.Form):
	dni = forms.CharField(
    	max_length=30, 
    	label='Número de Documento', 
    	validators=[
            RegexValidator(
                r'^[0-9]*$',
                'Sólo dígitos',
                'Número no válido'
            ),
            MinLengthValidator(5),
            MaxLengthValidator(30),
        ]
    )
	report_file = forms.FileField(label="Archivo de reporte")
	report_type = forms.ChoiceField(label="Tipo de reporte", choices=REPORT_TYPES_B)

reports/views.py
#encoding: utf-8
from django.shortcuts import render_to_response, redirect, HttpResponse
from django.template import RequestContext
from models import ReportForm
from users.models import SiteUser
from requisitions.models import Requisition
from studies.models import Study
import json
from django.core.urlresolvers import reverse_lazy
import os
from users.models import Notification
from reports.models import Candidate, ReportFile
from reports.forms import ReportRouterForm, ReportFileForm

# Create your views here.

def report_router(request, study_id):
	if request.method == 'GET':
		form = ReportRouterForm()
		return render_to_response('report_router.html', {'form':form}, context_instance=RequestContext(request))
	if request.method == 'POST':
		 form = ReportRouterForm(request.POST)
		 if form.is_valid():
		 	report_type = request.POST.get('report_type')

		 	if report_type == 'HV':
		 		return None
	 		elif report_type == 'LS':
	 			return redirect(reverse_lazy('reports:new_legal_report', args=(study_id,)))
 			elif report_type == 'SE':
 				return redirect(reverse_lazy('reports:new_verif_report', args=(study_id,)))

def create_legal_report(request, study_id):
	if request.method == 'GET':
		return render_to_response('legal_report.html', context_instance=RequestContext(request))
	
	if request.method == 'POST':
		fields = {}
		for field in request.POST:
			fields[field] = request.POST.get(field)

		candidate = Candidate.objects.get_or_create(dni_number=fields['dni_number'])[0]
		
		report = ReportForm.objects.update_or_create(
			study=Study.objects.get(id=study_id),
			candidate=candidate,
			report_type='LS'
		)[0]

		report.json_data = json.dumps(fields)
		

		report.save()

		return redirect(reverse_lazy('studies:view_study', kwargs={'study_id':str(study_id)}))

def create_verification_report(request, study_id):
	if request.method == 'GET':
		return render_to_response('verification_report.html', context_instance=RequestContext(request))
	
	if request.method == 'POST':
		fields = {}
		for field in request.POST:
			fields[field] = request.POST.get(field)
		
		report = ReportForm(
			study=Study.objects.get(id=study_id),
			json_data=json.dumps(fields),
			report_type='CV'
		)
		report.save()

		return redirect(reverse_lazy('studies:view_study', kwargs={'study_id':str(study_id)}))

from easy_pdf.rendering import render_to_pdf_response
def view_report(request, report_id):
	report = ReportForm.objects.get(id=report_id)
	
	if request.method == 'GET':
		data = json.loads(report.json_data)
		res_path = os.path.abspath(os.path.dirname(__file__)+"../../static/")
		return render_to_pdf_response(request, 'report.html', {'report':report, 'data':data, 'res_path':res_path})
		#return render_to_response('report.html', {'report':report, 'data':data, 'res_path':res_path})

def edit_report(request, report_id):

	report = ReportForm.objects.get(id=report_id)
	data = json.loads(report.json_data)

	if request.method == 'GET':
		if report.report_type == 'HV':
			return None
		elif report.report_type == 'LS':
			return render_to_response('legal_report.html', {'data':data}, context_instance=RequestContext(request))
		elif report.report_type == 'SE':
			return None

	if request.method == 'POST':
		fields = {}
		for field in request.POST:
			fields[field] = request.POST.get(field)
		
		report.json_data=json.dumps(fields)
		report.save()

		return redirect(reverse_lazy('studies:view_study', kwargs={'study_id':str(report.study_id)}))

def lock_report(request, report_id):
	report = ReportForm.objects.get(id=report_id)
	study_id = report.study.id
	report.locked = True
	report.save()
	notificate_report(request.user, study_id)

	return redirect(reverse_lazy('studies:view_study', args=(study_id,)))

def unlock_report(request, report_id):
	report = ReportForm.objects.get(id=report_id)
	study_id = report.study.id
	report.locked = False
	report.save()
	return redirect(reverse_lazy('studies:view_study', args=(study_id,)))

def check_report(request, report_id):
	report = ReportForm.objects.get(id=report_id)
	study_id = report.study.id
	report.verified = True
	report.save()
	return redirect(reverse_lazy('studies:view_study', args=(study_id,)))

def delete_report(request, report_id):
	report = ReportForm.objects.get(id=report_id)
	study_id = report.study.id
	report.delete()
	return redirect(reverse_lazy('studies:view_study', args=(study_id,)))







def upload_report(request, study_id):
	if request.method == 'GET':
		form = ReportFileForm()
		return render_to_response('upload_report.html', {'form':form, 'id':study_id}, context_instance=RequestContext(request))
	
	if request.method == 'POST':
		form = ReportFileForm(request.POST, request.FILES)
	
		if form.is_valid():
			dni = form.cleaned_data['dni']
			candidate = Candidate.objects.get_or_create(dni_number=dni)[0]
			study = Study.objects.get(id=study_id)
			rep_type = form.cleaned_data['report_type']
			rep_file = form.cleaned_data['report_file']


			new_report = ReportFile.objects.update_or_create(
				candidate=candidate,
				report_type=rep_type,
				study=study
			)[0]
			new_report.study = study
			new_report.report_file = rep_file
			new_report.save()

			update_study_status(study)

			return redirect(reverse_lazy('studies:view_study', kwargs={'study_id':str(study_id)}))
			
		return render_to_response('upload_report.html', {'form':form}, context_instance=RequestContext(request))

def edit_upload_report(request, ureport_id):
	report = ReportFile.objects.get(id=ureport_id)

	if request.method == 'GET':	
		form = ReportFileForm(initial={
			'report_type':report.report_type,
			'report_file':report.report_file,
			'dni':report.candidate.dni_number
		})
		return render_to_response('upload_report.html', {'form':form, 'editing':True, 'id':report.study.id}, context_instance=RequestContext(request))
	
	if request.method == 'POST':
		if request.FILES:
			form = ReportFileForm(request.POST, request.FILES)
		else:

			form = ReportFileForm(request.POST, {'report_file':report.report_file})
			
			print form.fields['report_file']


		if form.is_valid():
			dni = form.cleaned_data['dni']
			candidate = Candidate.objects.get_or_create(dni_number=dni)[0]
			study = Study.objects.get(id=report.study.id)
			rep_type = form.cleaned_data['report_type']
			rep_file = form.cleaned_data['report_file']

			report.candidate=candidate
			report.study = study
			report.report_type=rep_type
			report.report_file = rep_file
			
			report.save()
			update_study_status(study)
			join_reports(request, candidate.dni_number)

			return redirect(reverse_lazy('studies:view_study', kwargs={'study_id':str(report.study.id)}))
			
		return render_to_response('upload_report.html', {'form':form, 'editing':True, 'id':report.study.id}, context_instance=RequestContext(request))

def lock_upload_report(request, report_id):
	report = ReportFile.objects.get(id=report_id)
	study_id = report.study.id
	report.locked = True
	report.save()
	notificate_report(request.user, study_id)
	update_study_status(report.study)

	return redirect(reverse_lazy('studies:view_study', args=(study_id,)))

def unlock_upload_report(request, report_id):
	report = ReportFile.objects.get(id=report_id)
	study_id = report.study.id
	report.locked = False
	report.save()
	update_study_status(report.study)

	return redirect(reverse_lazy('studies:view_study', args=(study_id,)))

def check_upload_report(request, report_id):
	report = ReportFile.objects.get(id=report_id)
	study_id = report.study.id
	report.verified = True
	report.save()
	update_study_status(report.study)

	return redirect(reverse_lazy('studies:view_study', args=(study_id,)))

def delete_upload_report(request, report_id):
	report = ReportFile.objects.get(id=report_id)
	study_id = report.study.id
	report.delete()
	update_study_status(report.study)

	return redirect(reverse_lazy('studies:view_study', args=(study_id,)))


def search(request):
	if request.method == 'GET':
		reqs = []
		if request.user.is_superuser or request.user.is_staff:
			reqs = Requisition.objects.all()
		else:
			reqs = Requisition.objects.filter(client=request.user)
		
		return render_to_response('search.html', {'reqs':reqs}, context_instance=RequestContext(request))
	
	if request.method == 'POST':
		reports = []
		dni = request.POST.get('dni')
		
		try:
			reports = ReportFile.objects.filter(candidate__dni_number=dni, verified=True).order_by('report_type')

			join_reports(request, dni)
		except Exception, e:
			print e
		return render_to_response('search_results.html', {'reps':reports, 'dni':dni}, context_instance=RequestContext(request))

def search_by_req(request, req_id):
	
	reports = []
	if request.method == 'GET':
		reports = ReportFile.objects.filter(study__requisition_id=req_id, verified=True).values_list('candidate_id')
		candidates = Candidate.objects.filter(id__in=reports)

		return render_to_response('search_results.html', {'candidates':candidates, 'req_id':req_id}, context_instance=RequestContext(request))
		
	if request.method == 'POST':
		return None

from PyPDF2 import PdfFileMerger, PdfFileReader
from django.conf import settings
def join_reports(request, dni):
	try:
		candidate = Candidate.objects.get(dni_number=dni)
	except Exception, e:
		return False
		
	path = os.path.join(settings.MEDIA_ROOT,"uploads/reports/",dni)
	filename = path+"/reporte-"+dni+".pdf"
	
	reports = ReportFile.objects.filter(candidate__dni_number=dni, verified=True).order_by('report_type')
	merger = PdfFileMerger()
	for report in reports:
		report_file = os.path.join(
			settings.MEDIA_ROOT,report.report_file.name
		)
		merger.append(PdfFileReader(file(report_file, 'rb')))
	
	merger.write(str(filename))
	return filename


import zipfile
def compress_reports(request, req_id):
	
	path = os.path.join(settings.MEDIA_ROOT, "uploads/reports/reqs/")
	name = os.path.join(path,"requisicion_"+req_id+".zip")

	reports = ReportFile.objects.filter(study__requisition_id=req_id, verified=True).values_list('candidate_id')

reports/templates/report_router.html
{% extends "base.html"%}
{% load static %}

{% block title %}
	{% if editing %}
		Editar Estudio
	{% else %}
		Agregar Estudio
	{% endif %}
{% endblock %}

{% block imports %}
	<link href="{% static "css/chosen.min.css" %}" rel="stylesheet">
    <link href="{% static "css/chosen-bootstrap.css" %}" rel="stylesheet">
{% endblock %}

{% block content %}
	<h3 style="padding-left:20px;"><i class="fa fa-file-text"></i> 
		Crear reporte
	</h3>
	<hr style="border-color:#ddd;">


	<form class="form-horizontal col-md-10" id="add_user" method="POST" action="." enctype="multipart/form-data">
			{% csrf_token %}
			{% for field in form %}
				<div class="form-group">
				    <label class="col-sm-2 control-label">
				    	{{field.label}}
				    </label>
				    <div class="col-sm-10" style="margin-top:20px;">
				    	{% for error in field.errors %}
			    			<p class="text-danger">
			    				{{error.capitalize}}
			    			</p>
			    		{% endfor %}
				      	{{field}}
				    </div>
			  	</div>
			{% endfor %}
            

			<p class="text-right">
				{% if editing %}
				<a href="{% url "reqs:view_req" id %}" class="btn btn-default" >Cancelar</a>
				{% else %}
				<a href="{% url "reqs:home" %}" class="btn btn-default" >Cancelar</a>
				{% endif %}
				<button type="submit" class="btn btn-primary" >
					Crear Reporte
				</button>
			</p>
		</form>

{% endblock %}



{% block js_imports%}

	<script type="text/javascript" src="{% static "js/chosen.jquery.min.js" %}"></script>

	<script type="text/javascript">
	  	$(document).ready(function(){

  			$('#id_report_type').addClass('form-control').chosen();
	  			
	  	});

	</script>
	{{ form.media }}

{% endblock %}

reports/templates/search.html
{% extends "base.html"%}
{% load static %}

{% block title %}
	Buscar reportes
{% endblock %}

{% block imports %}
	<link href="{% static "css/chosen.min.css" %}" rel="stylesheet">
    <link href="{% static "css/chosen-bootstrap.css" %}" rel="stylesheet">
{% endblock %}

{% block content %}
	<h3 style="padding-left:20px;"><i class="fa fa-file-text"></i> 
		Buscar reportes
	</h3>
	<hr style="border-color:#ddd;">

	<form class="form-horizontal col-md-10" id="add_user" method="POST" action=".">
			{% csrf_token %}
			
			<div class="form-group">
			    <label class="col-sm-4 control-label">
			    	Buscar por documento de identidad
			    </label>
			    <div class="col-sm-8" style="margin-top:20px;">
			    	<input name="dni" type="text" class="form-control" />	
			    </div>
		  	</div>

		  	<div class="form-group">
			    <label class="col-sm-4 control-label">
			    	Buscar por requisición
			    </label>
			    <div class="col-sm-8" style="margin-top:20px;">
			    	<select id="search-box" class="form-control chosen-select">
			          <option></option>
			          {% for req in reqs %}
			            <option data-href="{% url "reports:search_req" req.id %}">
			                Requisición #{{req.id}}
			            </option>
			          {% endfor %}
			        </select>	
			    </div>
		  	</div>
            

			<p class="text-right">
				<button type="submit" class="btn btn-primary" >
					Buscar
				</button>
			</p>
		</form>

{% endblock %}



{% block js_imports%}

	<script type="text/javascript" src="{% static "js/chosen.jquery.min.js" %}"></script>

	<script type="text/javascript">
	  	$(document).ready(function(){

  			$('#id_report_type').addClass('form-control').chosen();
	  			
	  	});

	</script>
	{{ form.media }}

{% endblock %}

reports/templates/search_results.html
{% extends "base.html" %}
{% load static %}
{% load study_tags %}

{% block imports %}
  <link href="{% static "css/chosen.min.css" %}" rel="stylesheet">
  <link href="{% static "css/chosen-bootstrap.css" %}" rel="stylesheet">
  <link href="{% static "css/bootstrap-sortable.css" %}" rel="stylesheet">
{% endblock %}

{% block title %} 
  Reportes 
{% endblock %}

{% block content %}
	<div class="row mt">
		<div class="col-lg-12">
      <h3 class="inline" style="padding-left:20px;">
        <i class="fa fa-file-text"></i>
        {% if dni %}
          Reportes para el documento No. {{dni}}
        {% else%}
          Reportes para la requsición No. {{req_id}}
        {% endif %}
      </h3>
      <hr style="border-color:#ddd;">
      <div class="row-fluid">
        {% if dni %}
        <form class="form-horizontal col-md-12" id="add_user" method="POST" action=".">
          {% csrf_token %}
          
          <div class="form-group">
            <label class="col-sm-4 control-label">
              Buscar por documento de identidad
            </label>
            <div class="col-sm-4" style="margin-top:20px;">
              <input name="dni" type="text" class="form-control" /> 
            </div>
            <button class="col-sm-2 btn btn-primary" style="margin-top:20px;">Buscar</button>
          </div>
        </form>
        {% elif candidates %}
          <p class="text-right">
            <a href="{% url 'reports:compress_reports' req_id %}" class="btn btn-primary btn-lg">
              <span class="fa fa-download"></span>
              Bajar todos los reportes (.zip)
            </a>  
          </p>
        {% endif %}
      </div>
      <section id="unseen">
        <table class="table table-striped sortable">
          <thead>
            <tr>
              <th class="text-center" colspan="5">
                Reportes encontrados
              </th>
            </tr>
          </thead>
          <tbody>
            {% if not candidates %}
            <tr>
            
            <td class="text-center">
              {{dni}}  
            </td>
            {% if reps %}
              {% for report in reps %}
                  <td class="text-center">
                    <a href="/media/{{report.report_file}}" class="fa fa-download text-success">
                      {{report.get_report_type_display}}
                    </a>
                  </td>
              {% endfor %}
              <td class="text-center">
                <a href="/media/uploads/reports/{{reps.0.candidate.dni_number}}/reporte-{{reps.0.candidate.dni_number}}.pdf" class="fa fa-download text-success">
                  Informe completo
                </a>
              </td>
            {% else %}
                <td colspan="9" class="text-center">
                  <p class="alert alert-info">
                    No hay resultados
                  </p>
                </td>
            {% endif %}   
            </tr>
            {% else %}
              {% for candidate in candidates %}
                <tr>
                  <td>{{candidate.dni_number}}</td>
                  {% for report in candidate.reportfile_set.all %}
                    <td class="text-center">
                      {% if report.verified %}
                      <a href="/media/{{report.report_file}}" class="fa fa-download text-success">
                        {{report.get_report_type_display}}
                      </a>
                      {% endif %}
                    </td>
                    {% if forloop.counter == candidate.reportfile_set.all.count %}
                      {% if candidate.reportfile_set.all.count == 2 %}
                        <td></td>
                      {% elif candidate.reportfile_set.all.count == 1 %}
                        <td></td>
                        <td></td>
                      {% endif %}
                    {% endif %}
                  {% endfor %}
                  <td class="text-center">
                    <a href="/media/uploads/reports/{{candidate.dni_number}}/reporte-{{candidate.dni_number}}.pdf" class="fa fa-download text-success">
                      Informe completo
                    </a>
                  </td>
                </tr>
              {% endfor %}
            {% endif %}
          </tbody>
        </table>
      </section>
    </div>
	</div>
{% endblock %}

{% block js_imports %}
  <script type="text/javascript" src="{% static "js/bootstrap-sortable.js" %}"></script>
  <script type="text/javascript" src="{% static "js/chosen.jquery.min.js" %}"></script>
{% endblock %}

reports/templates/upload_report.html
{% extends "base.html"%}
{% load static %}

{% block title %}
	Subir estudio
{% endblock %}

{% block imports %}
	<link href="{% static "css/chosen.min.css" %}" rel="stylesheet">
    <link href="{% static "css/chosen-bootstrap.css" %}" rel="stylesheet">
{% endblock %}

{% block content %}
	<h3 style="padding-left:20px;"><i class="fa fa-upload"></i> 
		Subir estudio
	</h3>
	<hr style="border-color:#ddd;">

	<form class="form-horizontal col-md-10" id="add_user" method="POST" action="." enctype="multipart/form-data">
			{% csrf_token %}
			{% for field in form %}
				<div class="form-group">
				    <label class="col-sm-2 control-label">
				    	{{field.label}}
				    </label>
				    <div class="col-sm-10" style="margin-top:20px;">
				    	{% for error in field.errors %}
			    			<p class="text-danger">
			    				{{error.capitalize}}
			    			</p>
			    		{% endfor %}
				      	{{field}}
				    </div>
			  	</div>
			{% endfor %}
            

			<p class="text-right">
				<a href="{% url "studies:view_study" id %}" class="btn btn-default" >
					Cancelar
				</a>
				{% if editing %}
				<button type="submit" class="btn btn-primary" >
					Guardar Cambios
				</button>
				{% else %}
				<button type="submit" class="btn btn-primary" >
					Crear Reporte
				</button>
				{% endif %}
				
			</p>
		</form>

{% endblock %}



{% block js_imports%}

	<script type="text/javascript" src="{% static "js/chosen.jquery.min.js" %}"></script>

	<script type="text/javascript">
	  	$(document).ready(function(){

  			$('#id_report_type').addClass('form-control').chosen();
	  			
	  	});

	</script>
	{{ form.media }}

{% endblock %}