Ursus/urls.py
from django.conf.urls import patterns, include, url
from django.contrib.staticfiles.urls import static
from django.conf import settings
from two_factor.urls import urlpatterns as tf_urls

urlpatterns = patterns('',
	url(r'', include('authy.urls', 'authy')),
	url(r'^$', include('dashboard.urls', 'dashboard')),
	url(r'^registro/$', 'users.views.registry_client', name='registry'),
	url(r'^registro/continuar/$', 'users.views.new_profile', name='new_profile'),
	url(r'^admin/', include('admin.urls', 'admin')),
	url(r'^requisiciones/', include('requisitions.urls', 'reqs')),
	url(r'^estudios/', include('studies.urls', 'studies')),
	url(r'^reportes/', include('reports.urls', 'reports')),
	url(r'^configuracion/', include('settings.urls', 'settings')),

	url(r'^redactor/', include('redactor.urls')),
	
	url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {
        'document_root': settings.MEDIA_ROOT,
    }),

    url(r'', include(tf_urls, 'two_factor')),
    url(r'', include('user_sessions.urls', 'user_sessions')),
) + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

studies/urls.py
from django.conf.urls import patterns, include, url

urlpatterns = patterns(
    '',
    url(r'^$', 'studies.views.home', name='home'),
    url(r'^nuevo/$', 'studies.views.create_study', name='new_study'),
    url(r'^ver/(?P<study_id>\d+)/$', 'studies.views.view_study', name='view_study'),
    url(r'^editar/(?P<study_id>\d+)/$', 'studies.views.edit_study', name='edit_study'),
)

reports/models.py
#encoding: utf-8
from django.db import models
from studies.models import Study

# Create your models here.

REPORT_CHOICES = (
	('HV','Visita Domiciliaria'),
	('LS','Situación Jurídica'),
	('SS','Estudio de Seguridad'),
)

def get_path(instance,file):
	return 'uploads/reports/'+str(instance.candidate.dni_number)+"/"+file


class Candidate(models.Model):
	dni_number = models.CharField(max_length=20)
	class Meta:
		def __unicode__():
			return dni_number

class ReportForm(models.Model):
	study = models.ForeignKey(Study)
	candidate = models.ForeignKey(Candidate)
	json_data = models.TextField()
	report_type = models.CharField(max_length=2, choices=REPORT_CHOICES)
	locked = models.BooleanField(default=False)
	verified = models.BooleanField(default=False)

class ReportFile(models.Model):
	study = models.ForeignKey(Study)
	candidate = models.ForeignKey(Candidate, verbose_name=u'Cédula candidato')
	report_file = models.FileField(upload_to=get_path, verbose_name=u'Archivo')
	report_type = models.CharField(max_length=2, choices=REPORT_CHOICES, verbose_name=u'Tipo de reporte')
	locked = models.BooleanField(default=False)
	verified = models.BooleanField(default=False)

studies/models.py
#encoding: utf-8
from django.db import models
from django_resized import ResizedImageField
from django.core.validators import RegexValidator, MinLengthValidator, MaxLengthValidator
from requisitions.models import Requisition, Service
from django.contrib.auth.models import User
from redactor.fields import RedactorField

STUDY_STATUS = (
	('A','Asignado'),
	('R','En revisión'),
	('F','Terminado'),
)

def get_path(instance,file):
	return 'uploads/studies/'+str(instance.id)+file

class Study(models.Model):
	creation_date = models.DateTimeField(auto_now=True)
	requisition = models.ForeignKey(Requisition, verbose_name=u'Requisición', on_delete=models.CASCADE)
	service = models.ForeignKey(Service, verbose_name=u'Servicio')
	employee = models.ForeignKey(User, verbose_name=u'Empleado')
	limit_date = models.DateTimeField(verbose_name=u'Fecha de Entrega')
	description = RedactorField(verbose_name=u'Descripción')
	attachment = models.FileField(upload_to=get_path, verbose_name=u'Archivos adjuntos')
	observations = RedactorField(verbose_name=u'Observaciones', blank=True, null=True)
	status = models.CharField(max_length=1, default='A', verbose_name=u'Estado', choices=STUDY_STATUS)

studies/forms.py
#encoding: utf-8
from django import forms
from models import Study
from users.models import SiteUser
from django.forms.widgets import Select

class StudyForm(forms.ModelForm):
	
	class Meta:
		model = Study
		fields = '__all__'
		exclude = ['status']

	def __init__(self, *args, **kwargs):
		super(StudyForm, self).__init__(*args, **kwargs)
		employees = SiteUser.objects.filter(type='E')
		emps = [(employee.id, employee.first_name+' '+employee.last_name+' ('+employee.role+')') for employee in employees]
		self.fields['employee'].choices = emps

studies/views.py
#encoding: utf-8
from django.shortcuts import render_to_response, redirect
from django.template import RequestContext
from django.core.urlresolvers import reverse_lazy
from users.models import Notification
from django.core.mail import send_mail
from forms import StudyForm
from models import Requisition
from models import Study
from django.contrib.auth.models import User
from django.db.models import Q

def home(request):
	if request.user.is_superuser or request.user.is_staff:
		studies = Study.objects.all()
	elif request.user.type == 'C':
		studies = Study.objects.filter(requisition__client=request.user)
	else:
		studies = Study.objects.filter(~Q(status = 'F'),employee=request.user)
	
	studies = studies.order_by('-id')
	return render_to_response('studies_index.html', {'studies':studies}, context_instance=RequestContext(request))

def create_study(request, req_id=None):

	if request.method == 'GET':
		if req_id:
			form = StudyForm(initial={'requisition':req_id})
			return render_to_response('study.html', {'id':req_id, 'form':form}, context_instance=RequestContext(request))
		else:
			form = StudyForm()
			return render_to_response('study.html', {'form':form}, context_instance=RequestContext(request))
	
	if request.method == 'POST':
	
		form = StudyForm(request.POST, request.FILES)

		if form.is_valid():
			study = form.save()
			
			if request.FILES:
				study.attachment = request.FILES.get('attachment')
			
			study.save()
			study.requisition.status='P'
			study.requisition.save()

			notificate_assignation(study.employee, study.id)

			return redirect(reverse_lazy('studies:home'))
		
		return render_to_response('study.html', {'id':req_id,'form':form}, context_instance=RequestContext(request))

def view_study(request, study_id):
	if request.GET.get('notif'):
		not_id = request.GET.get('notif')
		notif = Notification.objects.get(id=not_id)
		notif.status=True
		notif.save()

	study = Study.objects.get(id=study_id)
	return render_to_response('study_detail.html', {'study':study}, context_instance=RequestContext(request))

def edit_study(request, study_id):
	study = Study.objects.get(id=study_id)

	if request.method == 'GET':
		form = StudyForm(instance=study)
		return render_to_response('study.html', {'r_id':study.requisition.id, 'id':study_id,'form':form, 'editing':True}, context_instance=RequestContext(request))
	
	if request.method == 'POST':
		form = StudyForm(request.POST, instance=study)
		if form.is_valid():
			study = form.save()
			return redirect(reverse_lazy('studies:view_study', kwargs={'study_id':str(study_id)}))

		return render_to_response('study.html', {'r_id':study.requisition.id, 'id':study_id,'form':form, 'editing':True}, context_instance=RequestContext(request))

from django.core.mail import send_mail
def notificate_assignation(site_user, element_id):

	notification = Notification(
		a_tag='',
		user=site_user,
		message='Se le ha asignado un nuevo estudio.</a>'.decode('utf-8'),
		short=u"Nueva asignación",
		icon="fa fa-search"
	)

	notification.save()
	notification.a_tag='<a href="/estudios/ver/'+str(element_id)+'?notif='+str(notification.id)+'">'
	notification.save()

	send_mail(
		subject=u'Nueva asignación', 
		message='Se le ha asignado un nuevo estudio.',
		html_message='<p>Se le ha asignado un nuevo estudio. Para mayor detalle use <a href="ursus.cosegem.com/estudios/ver/'+str(element_id)+'?notif='+str(notification.id)+'">este enlace</a></p>'.decode('utf-8'),
		from_email='Ursus <notificaciones.ursus@cosegem.com>',
		recipient_list=[site_user.email],
		fail_silently=False 
	)

studies/templates/assign_employees.html
{% extends "base.html" %}
{% load static %}
{% load study_tags %}

{% block imports %}
	<link href="{% static "css/chosen.min.css" %}" rel="stylesheet">
    <link href="{% static "css/chosen-bootstrap.css" %}" rel="stylesheet">
{% endblock %}

{% block title %}Asignar Empleados {% endblock %}
{% block content %}
	<h3 style="padding-left:20px;">
		<i class="fa fa-user"></i>
		Asignar Empleados (Estudio #{{id}})
	</h3>
	<hr style="border-color:#ddd;">
	
	<div class="col-lg-1">
		
	</div>
	<div class="col-lg-11">

		<form class="form-horizontal col-md-10" id="add_user" method="POST" action=".">
				{% csrf_token %}
				{% for role in roles %}
					<div class="form-group">
					    <label class="col-sm-2 control-label">
					    	{{role.name}}
					    </label>
					    <div class="col-sm-10" style="margin-top:20px;">
					    {% with role|get_employees as employees %}
					    	<select class="role_employees" name="role_{{role.id}}_employees">
						    	{% for employee in employees %}
						    		<option value="{{employee.id}}">
						    			{{employee.first_name}}
						    			{{employee.last_name}} 
						    		</option>	
						    	{% endfor %}
					    	</select>
					    	{% for error in field.errors %}
				    			<p class="text-danger">
				    				{{error.capitalize}}
				    			</p>
				    		{% endfor %}
					      	{{field}}
					    {% endwith %}
					    </div>
				  	</div>
				{% endfor %}
				<p class="text-right col-md-10" style="margin-top:10px;">
					<a href="{% url "studies:view_study" id %}" class="btn btn-default" >Cancelar</a>
					<button type="submit" class="btn btn-primary" >
						{% if editing %}
							Guardar cambios
						{% else %}
							Crear Asignación
						{% endif %}
					</button>
				</p>
		</form>
		
	</div>
	
{% endblock %}
{% block js_imports %}
  <script src="{% static "js/chosen.jquery.min.js" %}"></script>
  <script src="{% static "js/bootstrap-inputmask/bootstrap-inputmask.min.js" %}"></script>
  <script type="text/javascript">
  	$(document).ready(function(){
  		$('.role_employees').addClass('form-control').chosen({
  			placeholder_text_single:'Escribe para buscar...',
	        width: "80%",
	        search_contains: true
  		});
  	});
  </script>
{% endblock %}

studies/templates/edit_study.html
{% extends "base.html" %}
{% load static %}

{% block imports %}
	<link href="{% static "css/chosen.min.css" %}" rel="stylesheet">
    <link href="{% static "css/chosen-bootstrap.css" %}" rel="stylesheet">
{% endblock %}

{% block title %}Editar Estudio {% endblock %}
{% block content %}
	<h3 style="padding-left:20px;">
		<i class="fa fa-user"></i>
		Editar Estudio #{{id}} (Requisición #{{r_id}})
	</h3>
	<hr style="border-color:#ddd;">
	
	<div class="col-lg-1">
		
	</div>
	<div class="col-lg-11">

		<form class="form-horizontal col-md-10" id="add_user" method="POST" action=".">
				{% csrf_token %}
				{% for field in form %}
					<div class="form-group">
					    <label class="col-sm-2 control-label">
					    	{{field.label}}
					    </label>
					    <div class="col-sm-10" style="margin-top:20px;">
					    	{% for error in field.errors %}
				    			<p class="text-danger">
				    				{{error.capitalize}}
				    			</p>
				    		{% endfor %}
					      	{{field}}
					    </div>
				  	</div>
				{% endfor %}
				<p class="text-right col-md-10" style="margin-top:10px;">
					<a href="{% url "studies:view_study" id %}" class="btn btn-default" >Cancelar</a>
					<button type="submit" class="btn btn-primary" >
						{% if editing %}
							Guardar cambios
						{% else %}
							Crear Requisición
						{% endif %}
					</button>
				</p>
		</form>
		
	</div>
	
{% endblock %}
{% block js_imports %}
  <script src="{% static "js/chosen.jquery.min.js" %}"></script>
  <script src="{% static "js/bootstrap-inputmask/bootstrap-inputmask.min.js" %}"></script>
  <script type="text/javascript">
  	$(document).ready(function(){
  		$('#id_requisition, #id_candidate, #id_service').addClass('form-control').chosen({
  			placeholder_text_single:'Escribe para buscar...',
	        width: "80%",
	        search_contains: true
  		});
  	});
  </script>
{% endblock %}

studies/templates/studies_index.html
{% extends "base.html" %}
{% load static %}

{% block imports %}
  <link href="{% static "css/chosen.min.css" %}" rel="stylesheet">
  <link href="{% static "css/chosen-bootstrap.css" %}" rel="stylesheet">
  <link href="{% static "css/bootstrap-sortable.css" %}" rel="stylesheet">
{% endblock %}

{% block title %} Estudios {% endblock %}

{% block content %}
	<div class="row mt">
		<div class="col-lg-12">
      <h3 class="inline" style="padding-left:20px;">
        <i class="fa fa-search"></i> 
          Estudios <small>({{studies.count}} Estudios)</small>
      </h3>
      <hr style="border-color:#ddd;">
      <div class="row-fluid actions-bar">
        {% if user.is_superuser or user.is_staff%}
          <a href="{% url "studies:new_study"%}" class="btn btn-success">Agregar Estudio </a>
        {% else %}
          <b style="margin-right:10px;">Buscar: </b>
        {% endif %}
        
        <select id="search-box" class="form-control chosen-select">
          <option></option>
          {% for study in studies %}
            <option data-href="{% url "studies:view_study" study.id %}">
                Estudio #{{study.id}}
            </option>
          {% endfor %}
        </select>

      </div>
      <section id="unseen">
        <table class="table table-striped sortable">
          <thead>
            <tr>
              <th class="text-center">Nombre</th>
              <th class="text-center">Fecha</th>
              <th class="text-center hidden-xs">Requisición</th>
              <th class="text-center">Servicio</th>
              <th class="text-center">Fecha Entrega</th>
              <th class="text-center hidden-xs">Estado</th>
            </tr>
          </thead>
          <tbody>
            {% if studies %}
              {% for study in studies %}
                <tr>
                  <td class="text-center">
                    <a href="{% url "studies:view_study" study.id %}">
                      Estudio #{{study.id}}
                    </a>
                  </td>
                  <td class="text-center">
                    {{study.creation_date}}
                  </td>
                  <td class="text-center hidden-xs">
                    {{study.requisition}}
                  </td>
                  <td class="text-center hidden-xs">
                    {{study.service}}
                  </td>
                  <td class="text-center hidden-xs">
                    {{study.limit_date}}
                  </td>
                  <td class="text-center hidden-xs">
                    {{study.get_status_display}}
                  </td>
                </tr>            
              {% endfor %}
            {% else %}
              <tr>
                <td colspan="9" class="text-center">
                  <p class="alert alert-info">
                    No hay estudios registrados
                  </p>
                </td>
              </tr>
            {% endif %}   
          </tbody>
        </table>
      </section>
    </div>
	</div>
{% endblock %}

{% block js_imports %}
  <script type="text/javascript" src="{% static "js/bootstrap-sortable.js" %}"></script>
  <script type="text/javascript" src="{% static "js/chosen.jquery.min.js" %}"></script>
{% endblock %}

studies/templates/study.html
{% extends "base.html"%}
{% load static %}

{% block title %}
	{% if editing %}
		Editar Estudio
	{% else %}
		Agregar Estudio
	{% endif %}
{% endblock %}

{% block imports %}
	<link href="{% static "css/chosen.min.css" %}" rel="stylesheet">
    <link href="{% static "css/chosen-bootstrap.css" %}" rel="stylesheet">
    <link href="{% static "css/bootstrap-datetimepicker.css" %}" rel="stylesheet">
{% endblock %}

{% block content %}
	<h3 style="padding-left:20px;"><i class="fa fa-book"></i> 
		{% if editing %}
			Editar Estudio #{{id}}
		{% else %}
			Agregar Estudio
		{% endif %}
	</h3>
	<hr style="border-color:#ddd;">


	<form class="form-horizontal col-md-10" id="add_user" method="POST" action="." enctype="multipart/form-data">
			{% csrf_token %}
			{% for field in form %}
				<div class="form-group">
				    <label class="col-sm-2 control-label">
				    	{{field.label}}
				    </label>
				    <div class="col-sm-10" style="margin-top:20px;">
				    	{% for error in field.errors %}
			    			<p class="text-danger">
			    				{{error.capitalize}}
			    			</p>
			    		{% endfor %}
				      	{{field}}
				    </div>
			  	</div>
			{% endfor %}
            

			<p class="text-right">
				{% if editing %}
				<a href="{% url "studies:view_study" id %}" class="btn btn-default" >Cancelar</a>
				{% else %}
				<a href="{% url "reqs:home" %}" class="btn btn-default" >Cancelar</a>
				{% endif %}
				<button type="submit" class="btn btn-primary" >
					{% if editing %}
						Guardar cambios
					{% else %}
						Crear Estudio
					{% endif %}
				</button>
			</p>
		</form>

{% endblock %}



{% block js_imports%}

	<script type="text/javascript" src="{% static "js/chosen.jquery.min.js" %}"></script>
	<script type="text/javascript" src="{% static "js/moment-with-locales.js" %}"></script>
	<script type="text/javascript" src="{% static "js/bootstrap-datetimepicker.js" %}"></script>
	<script type="text/javascript">
	  	$(document).ready(function(){

  			$('#id_requisition, #id_employee, #id_service').addClass('form-control').chosen();
	  			
	  		$('#id_limit_date').parent().append(
		  		'<div class="input-group date" id="datetimepicker">\
	                <span class="input-group-addon">\
	                    <span class="glyphicon glyphicon-calendar"></span>\
	                </span>\
	            </div>'
		  	);
		  	$('#id_limit_date').prependTo('#datetimepicker');

		  	$('#datetimepicker').datetimepicker({'format':'DD/MM/YYYY HH:mm', sideBySide:true, locale:'es-CO', minDate:'{% now "m/d/Y H:i" %}'});
	  	});

	</script>
	{{ form.media }}

{% endblock %}

studies/templates/study_detail.html
{% extends "base.html" %}
{% load static %}
{% load study_tags %}
{% load humanize %}

{% block title %} Estudio #{{study.id}} {% endblock %}

{% block imports %}
  <link href="{% static "css/bootstrap-sortable.css" %}" rel="stylesheet">
{% endblock %}

{% block content %}
	<div class="row mt">
		<div class="col-lg-12">
	      	<h3 class="inline" style="padding-left:20px;">
	        	<i class="fa fa-book"></i> 
	          	Estudio #{{study.id}} <small>(Requisición {{study.requisition.id}})</small>
	      	</h3>
	      	<hr style="border-color:#ddd;">

	      	<div class="row mt">
				<div class="col-lg-12">
					<!-- WHITE PANEL - TOP USER -->
					<div class="white-panel pn">
						<div class="white-header">
							<h5>RESUMEN</h5>
						</div>
						
						<div class="row">
							<div class="col-md-3">
								<p><small>Solicitado por:</small></p>
								<p>
									<img src="{{MEDIA_URL}}{{ study.requisition.client.avatar }}" class="img-circle" width="50">
								</p>
								<p><b>{{study.requisition.client.first_name}} {{study.requisition.client.last_name}}</b></p>
							</div>
							<div class="col-md-2">
								<p class="small mt">FECHA</p>
								<p>{{study.creation_date|date:"d \d\e F \d\e Y"}}</p>
							</div>
							<div class="col-md-2">
								<p class="small mt">REQUISICIÓN</p>
								<p>{{study.requisition}}</p>
							</div>
							<div class="col-md-2">
								<p class="small mt">TIEMPO RESTATNTE</p>
								<p class="remove-msg">{{study.limit_date|naturaltime}}</p>
							</div>
							<div class="col-md-2">
								<p class="small mt">SERVICIO</p>
								<p>{{study.service}}</p>
							</div>
							<div class="col-md-2">
								<p class="small mt">ESTADO</p>
								<p>
									{{study.get_status_display}}
								</p>
							</div>
							<div class="col-md-2">
								<p class="small mt">EMPLEADO</p>
								<p>
									{{study.employee.first_name}}
									{{study.employee.last_name}}
								</p>
							</div>
							<div class="col-md-4">
								<a href="/media/{{study.attachment}}" target="_blank" download class="btn btn-default btn-lg" style="margin-top:5px;">
									<span class="fa fa-download"></span>
									Bajar archivos adjuntos
								</a>
							</div>

							<div class="col-md-12" style="margin-top:10px;">
								{% if user.is_superuser or user.is_staff %}
								<a href="{% url "studies:edit_study" study.id %}" class="btn btn-primary" style="width:30%">
									Modificar
								</a>
								{% endif %}
								
								{% if not user.type == 'C' %}
								<a href="{% url "reports:new_report" study.id %}" class="btn btn-success" style="width:30%">
									Crear Reporte
								</a>
								<a href="{% url "reports:upload_report" study.id %}" class="btn btn-primary" style="width:30%">
									Subir Reporte
								</a>
								{% endif %}
							</div>
							
							<div class="col-md-10 col-md-offset-1">
								<p style="margin-top:20px;" class="small mt">REPORTES</p>
							    <table class="table table-striped sortable">
									<thead>
							            <tr>
							              <th class="text-center">Tipo</th>
							              <th class="text-center">Doc. Candidato</th>
							              <th class="text-center">Estado</th>
							              <th class="text-center">Acción</th>
							            </tr>
							        </thead>
							        <tbody>
							            {% if study.reportform_set.all %}
							              {% for report in study.reportform_set.all %}
							                <tr>
							                  <td class="text-center">
							                      {{report.get_report_type_display}}
							                  </td>
							                  <td class="text-center">
							                      {{report.json_data|get_candidate}}
							                  </td>
							                  <td class="text-center">
							                    {% if report.verified %}
							                    	Listo
						                    	{% elif report.locked %}
						                    		En revisión
						                    	{% else %}
						                    		Para envío
							                    {% endif %}
							                  </td>
							                  <td class="text-center">
							                  	
						                    	{% if user.type == 'C' and report.verified %}
								                  	<a href="{% url 'reports:view_report' report.id %}" class="btn btn-primary">
							                    		<span class="fa fa-eye"></span>
							                    	</a>
						                    	{% elif not user.type == 'C' %}
						                    		<a href="{% url 'reports:view_report' report.id %}" class="btn btn-primary">
							                    		<span class="fa fa-eye"></span>
							                    	</a>
						                    	{% endif %}
						                    	{% if not user.type == 'C' %}
								                    {% if not report.locked or user.is_superuser %}
								                    	<a href="{% url 'reports:edit_report' report.id %}" class="btn btn-success">
								                    		<span class="fa fa-edit"></span>
								                    	</a>
								                    {% endif %}

								                    {% if not report.locked %}
								                    	<a href="{% url 'reports:lock_report' report.id %}" class="lock btn btn-warning">
								                    		<span class="fa fa-lock"></span>
								                    	</a>
								                    {% elif report.locked and user.is_superuser %}
								                    	<a href="{% url 'reports:unlock_report' report.id %}" class="btn btn-warning">
								                    		<span class="fa fa-unlock"></span>
								                    	</a>
								                    {% endif %}

								                    {% if not report.locked or user.is_superuser %}
								                    <a href="{% url 'reports:remove_report' report.id %}" class="delete btn btn-danger">
							                    		<span class="fa fa-trash-o"></span>
							                    	</a>
							                    	{% endif %}
							                    	{% if user.is_superuser %}
								                    	<a href="{% url 'reports:check_report' report.id %}" class="btn btn-default">
								                    		<span class="fa fa-check"></span>
								                    	</a>
								                    {% endif %}
							                    {% endif %}
							                  </td>
							                </tr>            
							              {% endfor %}
							            {% endif %}
						              	{% if study.reportfile_set.all %}

							              {% for report in study.reportfile_set.all %}
							                <tr>
							                  <td class="text-center">
							                      {{report.get_report_type_display}}
							                  </td>
							                  <td class="text-center">
							                      {{report.candidate.dni_number}}
							                  </td>
							                  <td class="text-center">
							                    {% if report.verified %}
							                    	Listo
						                    	{% elif report.locked %}
						                    		En revisión
						                    	{% else %}
						                    		Para envío
							                    {% endif %}
							                  </td>
							                  <td class="text-center">
							                  	{% if user.type == 'C' and report.verified %}
							                  	<a href="/media/{{report.report_file}}" class="btn btn-primary">
						                    		<span class="fa fa-eye"></span>
						                    	</a>
						                    	{% elif not user.type == 'C' %}
						                    		<a href="/media/{{report.report_file}}" class="btn btn-primary">
							                    		<span class="fa fa-eye"></span>
							                    	</a>
						                    	{% endif %}
						                    	{% if not user.type == 'C' %}
								                    {% if not report.locked or user.is_superuser %}
								                    	<a href="{% url 'reports:edit_report_upload' report.id %}" class="btn btn-success">
								                    		<span class="fa fa-edit"></span>
								                    	</a>
								                    {% endif %}

								                    {% if not report.locked %}
								                    	<a href="{% url 'reports:lock_report_upload' report.id %}" class="lock btn btn-warning">
								                    		<span class="fa fa-lock"></span>
								                    	</a>
								                    {% elif report.locked and user.is_superuser %}
								                    	<a href="{% url 'reports:unlock_report_upload' report.id %}" class="btn btn-warning">
								                    		<span class="fa fa-unlock"></span>
								                    	</a>
								                    {% endif %}

								                    {% if not report.locked or user.is_superuser %}
								                    <a href="{% url 'reports:remove_report_upload' report.id %}" class="delete btn btn-danger">
							                    		<span class="fa fa-trash-o"></span>
							                    	</a>
							                    	{% endif %}
							                    	{% if user.is_superuser %}
								                    	<a href="{% url 'reports:check_report_upload' report.id %}" class="btn btn-default">
								                    		<span class="fa fa-check"></span>
								                    	</a>
								                    {% endif %}
							                    {% endif %}
							                  </td>
							                </tr>            
							              {% endfor %}
							            {% endif %}
							            {% if not study.reportfile_set.all and not study.reportform_set.all%}
							              <tr>
							                <td colspan="4" class="text-center">
							                  <p class="alert alert-info">
							                    No se ha subido o creado ningún reporte.
							                  </p>
							                </td>
							              </tr>
							            {% endif %}   
							          </tbody>
								</table>
							</div>
						</div>
					</div>
				</div>
			</div>
    	</div>
	</div>
{% endblock %}

{% block js_imports%}
 <script type="text/javascript" src="{% static "js/bootstrap-sortable.js" %}"></script>
<script type="text/javascript">
	$(document).ready(function(){
		$('table').addClass('table table-bordered');
		$('#expand-panel').click(function(){
			$('#resume').toggleClass('col-lg-7 col-md-7 col-sm-7');
			$(this).html('Contraer Panel');
		});

		$('.lock, .delete').click(function(event){
			event.preventDefault();
			var aproval = confirm('Esta acción no se puede deshacer. ¿Desea continuar?')
			if(aproval){
				document.location.href = $(this).attr('href');
			}
		});
		$('.remove-msg').html($('.remove-msg').html().replace('a partir de ahora', ''));
	});
</script>

{% endblock %}